// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config';
import { defineConfig } from 'prisma/config';

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
  },
  datasource: {
    // O pooler em modo transaction (DATABASE_URL, porta 6543) e usado pela
    // aplicacao em runtime (src/database/prisma.service.ts), mas nao suporta
    // bem comandos de CLI (migrate/db pull travam). Para essas ferramentas,
    // usamos a conexao direta/session-mode (DIRECT_URL, porta 5432).
    url: process.env['DIRECT_URL'] ?? process.env['DATABASE_URL'],
  },
});
